### ISSUE TITLE
2021年7月活動概要：新規メンバーに重複がある

### ISSUE THREAD

**Issue by myakura** [w3ckeio/w3ckeio.github.io#16]
https://github.com/w3ckeio/w3ckeio.github.io/blob/7ce03d4891ab70141e40bbf8db1b9242cb6d2355/monthly-summary/202107.md#L110-L124

 * Sharing Economy Association of Korea (SEAK) 
 * Banksly 
 * Snake Nation

この3社もしくは団体が重複しています。コピー間違えか、書き換えミスでしょうか？

**Comment by himorin** [comment]
あ、newsletterからコピペしてくるときにissue間の重複確認してませんでした。
修正します。
